dist: trusty
sudo: required
language: go

go:
  - 1.9

services:
  - redis
  - mongodb

before_install:
  - make travis-before-build-step

install:
  - make travis-build-step

before_script:
  - git config --global user.email "marcelbelmont@gmail.com"
  - git config --global user.name "jbelmont"

script:
  - make travis-script-step

env:
  global:
    - secure: XR1gtkk5R+7UbgMs6pUxUkB4+RP67SR/3Q63CDf6wTv8gyxccTZ5ESXF6ii8k7iMPu8sPolN6EXTdVRV3kHN02CDr1kso00crPpn9eYFSUwEsTO5deh2/PK+po7rOKo+5QTjG1KPgeaQbkW/pdvE66PtHxH94WJ/6Ed2/yU2Atd3iKx8UInxgmOFpW1HeyrC55XBbxTcyQv+hMPqNKcrxZWJW4UU/qU88Pw5q9wEw0X8zrAF6O1asErgadsmhzBoD6dmlbNf1KFIrqujiIP21NEt+5DhtM4MV3iyNm3c9z4YnKWRzV6padrrW8enHVoKzQcbR9uzgHxoaAlsM6faaMmvrrjTcohDQK8fPtHxFTdN4W8JASJViEr/PUjZJvvcVAfKgRMgJY8FXL5aX68Le5WBK4PtMTWl7+0RdKtI66syc69q7pGJ79tbQa4ufv/CgBiI2WZPNftU5e+lFqlVfq8G3FZHkh0QRBL+FEU09x3ZKePxBh4oGLi3CCLcYu+nMwIL1R4IibNzm6xnxuXl/HwcJ5VGDQ1PC67E36jFeE+QGxjbQL1sRMaw+QgIYqijKapLz5/R7FvR0FG32v182XqV0dK/Wtze3/FxAsmi0n28FcdB9QqoEpOWNPCHaPeSPu49vVUIVzuZUP9G8Infjh3KrW1mRmcIKecHmDLOde0=
    - secure: EsTFNrkULKqNVSSaJvspXWUJm+y2RRKGKYbJz+sunPRkOuyoPy+YY2w84puqOfxIXwy8eHnlZnuzgY06mBA904jQ5omfS6I45cWAyQ8nn9ZQ6NJWa0zurBhh6kw2Dt0WQjX+WPrqkDt/rOgF9srAO1byNazpjQSP/47IiIXSgm37ybFIpm8eefapvVN3ErvgfvMJGz++SO/UpW0V8e/YUCbOrHRFwdNakmni3mzE244BR7PfD4JhddwFX+B9Bpsoo+P+7gDhtMkDDL1U7++19jy53bDHFI3JpuuFFeI2s5kiuM4adauK//CenUJeD5WsGbzmji2kK9vjHUjXsyx9tVEmv2Kn5fruAR/rHIul1NQZXvM0zG6sbAHDSKu+82Xvof+r2VoCfMxeyoTTuhmskGXY0EoB2wnRRdLECDWMXCrS5j6lPGINgibGkTBCQEHt7P4KXayn4GvQbgLjse/ddq+ypLjGmbzLMOs8UjZwbSWiH7HoBf/B34465eAQ/H4KTykxSaPy9Ih/N39QYBiQdBRr/EV+gH8L/8rOUUGDOLCzKaLo3xn/3mI32KFzvs1soXQ0eCxgvv1x8zwxhhuY2XEJvXq1TeKr/YQ9bzoQGJUTyKOAqSN4JY2CvRsAE+rCQYPk0lmLjSSkBaf2BKhws2UwXZfFsbhGtlvUx7Q8QdI=
