version: "3.3"
services:

  nginx1:
    image: nginx
    links:
      - wp1:wp1
      - wp2:wp2
      - wp3:wp3
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"

  mysql1:
    image: $mysql_image
    volumes:
      - db1_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$pass
      - MYSQL_DATABASE=$db
      - MYSQL_USER=$user
      - MYSQL_PASSWORD=$pass

  mysql2:
    image: $mysql_image
    volumes:
      - db2_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$pass
      - MYSQL_DATABASE=$db
      - MYSQL_USER=$user
      - MYSQL_PASSWORD=$pass

  mysql3:
    image: $mysql_image
    volumes:
      - db3_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$pass
      - MYSQL_DATABASE=$db
      - MYSQL_USER=$user
      - MYSQL_PASSWORD=$pass

  wp1:
    depends_on:
      - mysql1
    image: $wp_image
    ports:
      - "80"
    restart: always
    environment:
      - WORDPRESS_DB_NAME=$db
      - WORDPRESS_DB_USER=$user
      - WORDPRESS_DB_PASSWORD=$pass
    volumes:
      - wp1_data:$wp_data

  wp2:
    depends_on:
      - mysql2
    image: $wp_image
    ports:
      - "80"
    restart: always
    environment:
      - WORDPRESS_DB_NAME=$db
      - WORDPRESS_DB_USER=$user
      - WORDPRESS_DB_PASSWORD=$pass
    volumes:
      - wp2_data:$wp_data

  wp3:
    depends_on:
      - mysql3
    image: $wp_image
    ports:
      - "80"
    restart: always
    environment:
      - WORDPRESS_DB_NAME=$db
      - WORDPRESS_DB_USER=$user
      - WORDPRESS_DB_PASSWORD=$pass
    volumes:
      - wp3_data:$wp_data

  wpcli1:
    depends_on:
      - mysql1
      - wp1
    image: $wpcli_image
    links:
      - mysql1:mysql1
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10;
      wp --info;
      wp config list;
      wp config set DB_HOST mysql1;
      wp config set DB_NAME $db;
      wp config set DB_USER $user;
      wp config set DB_PASSWORD $pass;
      wp core install --path="$wp_data" --url="$url1" --title="$title1" --admin_user=$admin_user --admin_password=$admin_pass --admin_email=$email;
      '
    volumes:
     - wp1_data:$wp_data
    working_dir: $wp_data

  wpcli2:
    depends_on:
      - mysql2
      - wp2
    image: $wpcli_image
    links:
      - mysql2:mysql2
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10;
      wp --info;
      wp config list;
      wp config set DB_HOST mysql2;
      wp config set DB_NAME $db;
      wp config set DB_USER $user;
      wp config set DB_PASSWORD $pass;
      wp core install --path="$wp_data" --url="$url2" --title="$title2" --admin_user=$admin_user --admin_password=$admin_pass --admin_email=$email;
      '
    volumes:
     - wp2_data:$wp_data
    working_dir: $wp_data

  wpcli3:
    depends_on:
      - mysql3
      - wp3
    image: $wpcli_image
    links:
      - mysql3:mysql3
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10;
      wp --info;
      wp config list;
      wp config set DB_HOST mysql3;
      wp config set DB_NAME $db;
      wp config set DB_USER $user;
      wp config set DB_PASSWORD $pass;
      wp core install --path="$wp_data" --url="$url3" --title="$title3" --admin_user=$admin_user --admin_password=$admin_pass --admin_email=$email;
      '
    volumes:
     - wp3_data:$wp_data
    working_dir: $wp_data

volumes:
  db1_data:
  wp1_data:
  db2_data:
  wp2_data:
  db3_data:
  wp3_data:
