services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    container_name: 'gitlab-nima-tutorial'
    restart: always
    hostname: 'gitlabtest.domain.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlabtest.domain.local'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
      - '587:587'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
