version: '3.9'
services:
  db1:
    image: mysql:latest
    env_file:
      - .env
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db1_data:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - db1
  mongodb1:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
volumes:
  db1_data:
  mongodb:
  mongoconfig:
