# Generated by Django 3.1.2 on 2020-11-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveSmallIntegerField(db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.timeline')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['rank'],
            },
        ),
    ]
