---

- name: Backup config all devices
  hosts: all

  tasks:
  - name: backup the running-config
    cisco.ios.ios_config:
      backup: yes
      backup_options:
        dir_path: /home/rizqi/cisco-devnet/ansible/backup

