---

- name: automate switch configuration using ansible
  hosts: all

  tasks:

  - name: configure the login banner
    cisco.ios.ios_banner:
      banner: login
      text: |
        ************************************************************
        * SWITCH IDN.ID                                            *
        * Dilarang masuk tanpa izin.                               *
        * Tindakan merusak sistem diancam pidana.                  *
        ************************************************************
      state: present

#  - name: Create VLAN
#      cisco.ios.ios_vlans:
#      config:
#      - name: VLAN-IT
#        vlan_id: 10
#      - name: VLAN-Guests
#        vlan_id: 20

#  - name: Configure access and trunking interfaces
#      cisco.ios.ios_l2_interfaces:
#      config:
#      - name: GigabitEthernet1/1
#        mode: access
#        access:
#          vlan: 10
#      - name: GigabitEthernet1/2
#        mode: trunk
#        trunk:
#          allowed_vlans: 10,20
#          native_vlan: 20
#          encapsulation: dot1q
#      state: merged

#  - name: Create new acl into device
#    cisco.ios.ios_config:
#      lines:
#      - 10 deny ip host 192.0.2.1 any log
#      - 110 deny ip host 192.0.0.5 any log
#      - 9999 permit ip any any
#      parents: ip access-list extended block
#      before: no ip access-list extended block
#      match: exact

#  - name: Assign ACL to interface
#    cisco.ios.ios_config:
#      lines:
#      - ip access-group block in
#      parents: interface G3/0

#  - name: backup the running-config
#    cisco.ios.ios_config:
#      backup: yes
#      backup_options:
#        dir_path: /home/rizqi/cisco-devnet/ansible/backup

