# We have 2 stages >> Test and Deploy
stages:
  - test
  - deploy

# Config cache
cache:
  paths:
    - node_modules/

# Test job
test:
  # Docker image
  image: node:latest
  # Attach test job to test stage
  stage: test
  # Config to use GitLab Shared Runner with Executor Docker
  # tags:
  #   - docker
  script:
    - npm install
    - npm run test
  # Defines the names of branches and tags the job runs for
#   only:
#     - develop

# Deploy job
deploy:
  # Docker image
  image: node:latest
  # type: deploy
  # Attach deploy job to deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  # tags:
  #   - my-shell-runner
  script:
    # Only copy changed files to project folder
    # - cp -r -u * $PROJECT_DIR
    # - cd $PROJECT_DIR
    - npm install
    - npm run test
    - npm start
    # Restart NodeJS service
    # - forever stop index.js || true
    # - forever start index.js
#   only:
#     - develop
