- hosts: all
  tasks: 
  - name: print stdout
    command: echo "hello there"
    register: hello
  - debug: msg="stdout={{ hello.stdout }}"
  - debug: msg="stderr={{ hello.stderr }}"
  - debug:
      msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
  - debug:
      msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
