# install-suricata-on-ubuntu-20

# Suricata is a Network Security Monitoring (NSM) tool that uses sets of community created and user defined signatures (also referred to as rules) to examine and process network traffic. Suricata can generate log events, trigger alerts, and drop traffic when it detects suspicious packets or requests to any number of different services running on a server.

# By default Suricata works as a passive Intrusion Detection System (IDS) to scan for suspicious traffic on a server or network. It will generate and log alerts for further investigation. It can also be configured as an active Intrusion Prevention System (IPS) to log, alert, and completely block network traffic that matches specific rules.

# You can deploy Suricata on a gateway host in a network to scan all incoming and outgoing network traffic from other systems, or you can run it locally on individual machines in either mode.

sudo add-apt-repository ppa:oisf/suricata-stable
sudo apt install suricata
sudo systemctl enable suricata.service
sudo systemctl stop suricata.service

# The Suricata package from the OISF repositories ships with a configuration file that covers a wide variety of use cases. The default mode for Suricata is IDS mode, so no traffic will be dropped, only logged. Leaving this mode set to the default is a good idea as you learn Suricata. Once you have Suricata configured and integrated into your environment, and have a good idea of the kinds of traffic that it will alert you about, you can opt to turn on IPS mode.

# However, the default configuration still has a few settings that you may need to change depending on your environment and needs.

# Suricata can include a Community ID field in its JSON output to make it easier to match individual event records to records in datasets generated by other tools.

# If you plan to use Suricata with other tools like Zeek or Elasticsearch, adding the Community ID now is a good idea.

sudo nano /etc/suricata/suricata.yaml
sudo vi /etc/suricata/suricata.yaml

      # Community Flow ID
      # Adds a 'community_id' field to EVE records. These are meant to give
      # records a predictable flow ID that can be used to match records to
      # output of other tools such as Zeek (Bro).
      #
      # Takes a 'seed' that needs to be same across sensors and tools
      # to make the id less predictable.

      # enable/disable the community id feature.
      community-id: true

sudo cat /etc/suricata/suricata.yaml | grep community-id

ip -p -j route show default

sudo nano /etc/suricata/suricata.yaml
sudo vi /etc/suricata/suricata.yaml

af-packet:
  - interface: eth0
    # Number of receive threads. "auto" uses the number of cores
    #threads: auto
    # Default clusterid. AF_PACKET will load balance packets based on flow.
    cluster-id: 99

 #  For eBPF and XDP setup including bypass, filter and load balancing, please
    #  see doc/userguide/capture-hardware/ebpf-xdp.rst for more info.

  - interface: enp0s1
    cluster-id: 98

  - interface: default
    #threads: auto
    #use-mmap: no
    #tpacket-v3: yes

detect-engine:
  - rule-reload: true

sudo kill -usr2 $(pidof suricata)
sudo suricata-update

sudo suricata-update list-sources
sudo suricata-update enable-source tgreen/hunting
sudo suricata -T -c /etc/suricata/suricata.yaml -v
sudo systemctl start suricata.service
sudo systemctl status suricata.service
sudo tail -f /var/log/suricata/suricata.log
curl http://testmynids.org/uid/index.html
grep 2100498 /var/log/suricata/fast.log
sudo apt install jq
jq 'select(.alert .signature_id==2100498)' /var/log/suricata/eve.json

