version: '3'
services:
      ansible:
        container_name: ansible
        image: ansible
        tty: true
        stdin_open: true
        build:
          context: ./
      remote-host-one:
        container_name: remote-host-one
        image: remote-host-ssh
        build:
          context: ./ssh-enabled-ubuntu
networks:
      net:
