version: "3"

services:
  php:
    build: # Info to build the Docker image
      context: . # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: Dockerfile-php # Specify the name of the Dockerfile
    environment: # You can use this section to set environment variables. But you can also use the .env file.
     - DATABASE_URL=mysql://root:root@db:3306/project_db # Connection string for the database.
     - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages # AMQP connection string
    volumes:
     - ./project/:/var/www/project/ # Location of the project for php-fpm. Note this should be the same for NGINX.
    networks:
     - symfony # Docker containers (services) that need to connect to each other should be on the same network.

  php-consume:
    build:
      context: .
      dockerfile: Dockerfile-php-consume
    environment:
     - DATABASE_URL=mysql://root:root@db:3306/project_db
     - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
    volumes:
     - ./project/:/var/www/project/
    networks:
     - symfony

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
     - ./project/:/var/www/project/
    ports:
     - 8001:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    networks:
     - symfony

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
     - MYSQL_ROOT_PASSWORD=root # Setting the MYSQL credentials to root:root.
    volumes:
     - symfony_db:/var/lib/mysql:cached # Persist the database in a Docker volume.
    ports:
     - 3311:3306
    networks:
     - symfony

  rabbitmq: # The RabbitMQ container.
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    ports:
     - 15672:15672
    volumes:
     - rabbitmq:/var/lib/rabbitmq:cached
    networks:
     - symfony

volumes:
  symfony_db:
  rabbitmq:

networks:
 symfony:
